#! /bin/bash

testerDirectory=/home/ssdavis/60/p3/Testing
if [ $# -ne 1 ]; then
  echo "testhw usage: testhw gen_directory"
  exit
fi

cd $1
rm -f *.out *.o out*.txt result*.txt input*    &> /dev/null
cp -f $testerDirectory/shakespeare.txt .
echo -n "Scores from p3 for " > results.txt

if [ -e authors.csv ]; then
  dos2unix -q authors.csv
  awk -F, {'for (i = 2; i <= NF; ++i) printf"%s ", $i'} authors.csv >> results.txt
  echo -e "\n"
  awk -F, 'NR < 4 {for (i = 2; i <= NF; ++i) printf"%s", $i; printf"\n";}' authors.csv > names.txt
  echo -e "\nNote that format is: e-mail<comma>last name<comma>first name" >> results.txt
  echo "For example: ssdavis@ucdavis.edu,Davis,Sean"  >> results.txt
  awk -F, {'printf"%s ", $1'} authors.csv > addresses
else
  echo  "You need to create an authors.csv file!!!! No one will receive credit for this assignment"  >> results.txt
  echo "$1@ucdavis.edu" > addresses
  finger ${PWD##*/} | awk 'NR == 1 {printf"%s,%s", $5, $4}' > names.txt
fi


echo -en "\nAddresses used: " >> results.txt 
cat addresses >> results.txt
echo " " >> results.txt
echo "Directory: $1"

genScore=0

echo -e "\ngen.cpp:" >>results.txt
if [ ! -e gen.cpp ]; then
  echo "gen.cpp not found." >> results.txt
else  # gen.cpp found
  grep -e '#include *<' gen.cpp | egrep -v "(iostream|iomanip|fstream|cstring|cctype|cstdlib)"  > temp
  if [ -s temp ]; then
    echo "#include of system header file other than iostream, iomanip, fstream," >> results.txt
    echo "cctype, cstdlib, or cstring in gen.cpp so zero."  >> results.txt
  else # No violation of specs
    g++ -o gen.out gen.cpp

    if [ ! -e gen.out ]; then # gen.out not found
      echo "gen.cpp does not compile!"  >> results.txt
    else #gen.out create  
       (gen.out shakespeare.txt > shakespeareIndex.txt )&
       sleep 2
       pkill gen.out &> /dev/null
       rm core &> /dev/null
       diff shakespeareIndex.txt  $testerDirectory/shakespeareIndex.txt > temp

      if [ -s temp ]; then
        echo "Your output does not match Sean's, so you will receive 0/10 points." >> results.txt
        head -10 temp >> results.txt
      else
        echo "Your ouput matched Sean's, so you will receive 10/10 points." >> results.txt
        genScore=10   
      fi # if runtime errors
    fi # if gen.out not found
  fi # if design violation
fi # if gen.cpp found



#  mailx -s "ECS 60 P3 Test Results" `cat addresses` < results.txt

# awk 'NR == 1 {printf"%s,", $0}' names.txt >> ../results.csv
#echo "${1%%/},$genScore" >> ../results.csv
#authorCount=$(grep "@" authors.csv | wc -l)

#if [ $authorCount -gt 1 ]; then
#  awk 'NR == 2 {printf"%s,", $0}' names.txt >> ../results.csv
#  echo "${1%%/},$genScore" >> ../results.csv
#fi
